- name: Set up Journalling and Auditing
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Display a message
      debug:
        msg: "Starting journaling and auditing setup."

    - name: Ensure required packages are installed (auditd, audispd-plugins)
      package:
        name: "{{ item }}"
        state: present
      loop:
        - auditd
        - audispd-plugins

    - name: Ensure journald is configured for persistent storage
      lineinfile:
        path: /etc/audit/plugins.d/syslog.conf
        regexp: '^#?Storage='
        line: 'Storage=persistent'
        state: present
      notify: restart systemd-journald

    - name: Tune journald max use (optional)
      lineinfile:
        path: /etc/systemd/journald.conf
        regexp: '^#?SystemMaxUse='
        line: 'SystemMaxUse=500M'
        state: present
      notify: restart systemd-journald

    - name: Deploy audit rules for sudoers changes
      copy:
        src: files/99-sudoers.rules
        dest: /etc/audit/rules.d/99-sudoers.rules
        owner: root
        group: root
        mode: '0644'
      notify: restart auditd

    - name: Ensure audisp syslog plugin is active (send audit to syslog/journal)
      lineinfile:
        path: /etc/audisp/plugins.d/syslog.conf
        regexp: '^active = '
        line: 'active = yes'
        state: present
      notify: restart auditd

    - name: Deploy journal helper scripts
      copy:
        src: "tole_project/scripts/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: root
        group: root
        mode: '0755'
      loop:
        - journal_search.sh
        - journal_filter_services.sh
        - journal_watch_alert.sh

  handlers:
    - name: restart systemd-journald
      systemd:
        name: systemd-journald
        state: restarted
        daemon_reload: yes
      become: yes

    - name: restart auditd
      systemd:
        name: auditd
        state: restarted
      become: yes
