- name: SIS 3 - Packages and Firewall
  hosts: localhost
  connection: local
  become: yes
  vars:
    prometheus_version: "2.53.1"
    grafana_version: "11.1.0"

  tasks:
    - name: "--- SIS 3: PACKAGES AND FIREWALL ---"
      tags: packages
      block:
        - name: Install system packages
          ansible.builtin.apt:
            name:
              - build-essential
              - python3-pip
              - python3-dev
              - mysql-server
              - libmysqlclient-dev
              - pkg-config
              - ufw
              - wget
            state: present
            update_cache: yes

        - name: Install Python packages
          ansible.builtin.pip:
            name:
              - django
              - gunicorn
              - mysqlclient
              - prometheus-client
            executable: pip3
            state: present
            extra_args: --break-system-packages

        - name: Download and unarchive Prometheus
          ansible.builtin.unarchive:
            src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
            dest: /tmp/
            remote_src: yes
            creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"

        - name: Install Prometheus Binaries
          shell: |
            mv /tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus /usr/local/bin/
            mv /tmp/prometheus-{{ prometheus_version }}.linux-amd64/promtool /usr/local/bin/
            mv /tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml /etc/prometheus/
            chown prometheus:monitoring /usr/local/bin/prometheus
            chown prometheus:monitoring /usr/local/bin/promtool
          args:
            creates: /usr/local/bin/prometheus

        - name: Download and unarchive Grafana
          ansible.builtin.unarchive:
            src: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
            dest: /tmp/
            remote_src: yes

        - name: Install Grafana Binaries
          shell: |
            mv /tmp/grafana-*/bin/grafana /usr/local/bin/
            mv /tmp/grafana-*/bin/grafana-server /usr/local/bin/
            mv /tmp/grafana-*/bin/grafana-cli /usr/local/bin/
            chown -R grafana:monitoring /usr/local/bin/grafana*
          args:
            creates: /usr/local/bin/grafana-server
